### ISSUE TITLE
Plugin doesn't work in Jekyll >= 3.0.0

### ISSUE THREAD

**Issue by mr-infty** [mpalmer/jekyll-static-comments#24]
As of version 3.0.0, the class `Jekyll::Post` no longer exists: trying to run this plugin results in the error

    jekyll 3.7.3 | Error:  undefined method `to_liquid' for class `Jekyll::Post'

Proposed fix: Rename `Jekyll:Post` to `Jekyll:Document` in `static_comments.rb`.
